
import { useVagasStore } from './src/store/vagasStore';

const mockData = [
  {
    id: 'vaga-test-1',
    unidade: 'HECAD',
    cargo: 'ENFERMEIRO - UTI PEDIÁTRICA',
    requisicao: 'REQ-001',
    numero_requisicao: 'REQ-001',
    data_abertura: '2024-03-01',
    data_recebimento: '2024-03-05',
    numero_vagas: 2,
    quantidade: 2,
    secao: 'UTI',
    tipo_vaga: 'substituicao',
    status: 'em_edital',
    status_geral: 'em_edital',
    analista_responsavel: 'Ana Souza',
    assistentes: ['Carlos Silva'],
    vaga: 'V-001',
    observacoes_internas: 'Urgente',
    origem_importacao: 'test.xlsm',
    data_importacao: new Date().toISOString(),
    lote_importacao: 'BATCH-001',
    source_sheet: 'tb_HECAD',
    source_row_index: 4,
    tem_banco_valido: false,
    historico: []
  },
  {
    id: 'vaga-test-2',
    unidade: 'HUGOL',
    cargo: 'TÉCNICO DE ENFERMAGEM',
    requisicao: 'REQ-002',
    numero_requisicao: 'REQ-002',
    data_abertura: '2024-03-02',
    data_recebimento: '2024-03-06',
    numero_vagas: 5,
    quantidade: 5,
    secao: 'Emergência',
    tipo_vaga: 'aumento',
    status: 'publicar_novo_edital',
    status_geral: 'publicar_novo_edital',
    analista_responsavel: 'Marcos Lima',
    assistentes: [],
    vaga: 'V-002',
    observacoes_internas: '',
    origem_importacao: 'test.xlsm',
    data_importacao: new Date().toISOString(),
    lote_importacao: 'BATCH-001',
    source_sheet: 'tb_HUGOL',
    source_row_index: 5,
    tem_banco_valido: false,
    historico: []
  },
  {
    id: 'vaga-test-3',
    unidade: 'CRER',
    cargo: 'FISIOTERAPEUTA',
    requisicao: 'REQ-003',
    numero_requisicao: 'REQ-003',
    data_abertura: '2024-03-10',
    data_recebimento: '2024-03-12',
    numero_vagas: 1,
    quantidade: 1,
    secao: 'Reabilitação',
    tipo_vaga: 'lideranca',
    status: 'admissao_efetivada',
    status_geral: 'admissao_efetivada',
    analista_responsavel: 'Juliana Costa',
    assistentes: [],
    vaga: 'V-003',
    observacoes_internas: '',
    origem_importacao: 'test.xlsm',
    data_importacao: new Date().toISOString(),
    lote_importacao: 'BATCH-001',
    source_sheet: 'tb_CRER',
    source_row_index: 6,
    tem_banco_valido: true,
    historico: []
  }
];

// This is just a helper to inject data via console if needed, 
// but I'll try to find a way to set it in the browser directly.
console.log('Injected data:', mockData);
